name: ci-docs

on:
  schedule:
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
  # This is meant to run at 14:17 UTC on 11th and 26th of every month
    - cron: '17 14 11 * *'
    - cron: '17 14 26 * *'
  push:
    branches:
      - main
    paths:
      - '.github/actions/build-ci-image/**'
      - '.github/actions/merge-ci-images/**'
      - '.github/workflows/ci-docs.yml'
      - 'ci/docs/**'
  workflow_dispatch:

env:
  REGISTRY_IMAGE: libfn.azurecr.io/ci-docs

jobs:
  build:
    if: ${{ github.repository == 'libfn/functional' }}
    runs-on:
      group: ${{ matrix.platform == 'linux/arm64' && 'runners-arm64' || 'runners-intel' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - uses: ./.github/actions/build-ci-image
        with:
          platform: ${{ matrix.platform }}
          image: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
          registry: libfn.azurecr.io
          username: ${{ secrets.AZURECR_NAME }}
          password: ${{ secrets.AZURECR_PASS }}
          context: "ci/docs"
          title: "docs"
          push: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}

  merge:
    if: ${{ github.repository == 'libfn/functional' && github.ref_type == 'branch' && github.ref_name == 'main' }}
    runs-on:
      group: runners-intel
    needs:
      - build

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - uses: ./.github/actions/merge-ci-images
        with:
          image: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
          registry: libfn.azurecr.io
          username: ${{ secrets.AZURECR_NAME }}
          password: ${{ secrets.AZURECR_PASS }}
          title: "docs"
